const { SlashCommandBuilder } = require("discord.js");
const embedTemplate = require("../../utils/embedTemplate");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("regen")
    .setDescription("Send the regenerated link embed"),

  async execute(interaction) {
    const staffRoleId = "1481953107448692860"; // Staff role

    // Permission check
    if (!interaction.member.roles.cache.has(staffRoleId)) {
      return interaction.reply({
        content: "You do not have permission to use this command.",
        flags: 64
      });
    }

    await interaction.deferReply({ flags: 64 });

    const host = interaction.user;

    // Find latest release embed
    const messages = await interaction.channel.messages.fetch({ limit: 50 });
    const releaseMessage = messages.find(m =>
      m.embeds[0]?.title?.includes("Session Release")
    );

    const description =
      `> <:arrowright:1523736161770672209> The session link has been regenerated by ${host}. Please wait for reinvites to commence.`;

    const { embed } = embedTemplate({
      title: "<:shines:1524097104547680276> Greenville Roleplay East - *__Link Regenerated__* <:shines:1524097104547680276>",
      description
    });

    // Reply to release embed if found
    if (releaseMessage) {
      await releaseMessage.reply({ embeds: [embed] });
    } else {
      await interaction.channel.send({ embeds: [embed] });
    }

    await interaction.editReply({
      content: "Regenerated link embed sent successfully."
    });
  }
};
